#!/usr/bin/env python3
"""
build_submission.py — Merges strategy modules into a single submission.py.

Usage:
    python tools/build_submission.py
"""

import ast
import os
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
STRATEGIES_DIR = ROOT / "strategies"
OUTPUT = ROOT / "submission.py"
DATAMODEL = ROOT / "datamodel.py"

HEADER = '''# AUTO-GENERATED by tools/build_submission.py — do not edit by hand.
from datamodel import OrderDepth, TradingState, Order
from typing import List, Dict
import json
import math

'''

TRADER_CLASS = '''
class Trader:
    def run(self, state: TradingState):
        # Safe default template: place no orders.
        # Returning unknown product keys can crash some backtester configs.
        return {}, 0, ""
'''


def collect_strategy_source() -> str:
    parts = []
    for path in sorted(STRATEGIES_DIR.glob("*.py")):
        if path.name == "__init__.py":
            continue
        src = path.read_text(encoding="utf-8")
        # Strip relative imports — they won't work in the merged file
        lines = [l for l in src.splitlines() if not l.startswith("from strategies")]
        parts.append(f"# --- {path.name} ---\n" + "\n".join(lines))
    return "\n\n".join(parts)


def build():
    strategy_src = collect_strategy_source()
    output = HEADER + strategy_src + TRADER_CLASS
    OUTPUT.write_text(output, encoding="utf-8")
    print(f"Submission written to {OUTPUT}  ({len(output)} chars)")


if __name__ == "__main__":
    build()
