# AUTO-GENERATED by tools/build_submission.py — do not edit by hand.
from datamodel import OrderDepth, TradingState, Order
from typing import List, Dict
import json
import math

# --- base.py ---
from datamodel import OrderDepth, TradingState, Order
from typing import List


class ProductTrader:
    """
    Base class for all per-product strategy implementations.
    Subclass this and implement `get_orders`.
    """

    def __init__(self, symbol: str, position_limit: int):
        self.symbol = symbol
        self.position_limit = position_limit

    def get_orders(self, state: TradingState) -> List[Order]:
        raise NotImplementedError

    # --- state persistence (round-trips through traderData JSON) ---

    def load_state(self, data: dict) -> None:
        """Called by Trader.run() before get_orders. Restore instance state from data."""

    def dump_state(self, data: dict) -> None:
        """Called by Trader.run() after get_orders. Write instance state back into data."""

    # --- helpers ---

    def best_bid(self, order_depth: OrderDepth) -> int | None:
        return max(order_depth.buy_orders) if order_depth.buy_orders else None

    def best_ask(self, order_depth: OrderDepth) -> int | None:
        return min(order_depth.sell_orders) if order_depth.sell_orders else None

    def mid_price(self, order_depth: OrderDepth) -> float | None:
        bid = self.best_bid(order_depth)
        ask = self.best_ask(order_depth)
        if bid is not None and ask is not None:
            return (bid + ask) / 2
        return None

    def current_position(self, state: TradingState) -> int:
        return state.position.get(self.symbol, 0)

# --- ash_mm.py ---
from datamodel import Order, TradingState
from typing import List

SYMBOL = "ASH_COATED_OSMIUM"
POSITION_LIMIT = 50

# ASH is stationary around 10,000.  A very slow EMA lets the fair value
# drift with any multi-day structural shift without chasing tick noise.
EMA_ALPHA = 0.02
FAIR_VALUE_INIT = 10_000

# We quote ±QUOTE_HALF ticks from fair value as passive limit orders.
# The market spread is ~16 ticks, so ±4 puts us well inside and earns
# most of the spread while still being passive.
QUOTE_HALF = 4

# Inventory skew: shift both quotes by position / SKEW_DIVISOR so that
# a long inventory cheapens our ask and a short inventory raises our bid.
SKEW_DIVISOR = 5

# Aggressive take edge: cross the market only when the price offered is
# more than TAKE_EDGE ticks through fair value (genuine mispricing).
TAKE_EDGE = 2


class AshMarketMaker(ProductTrader):
    """
    Passive market-maker for ASH_COATED_OSMIUM.

    Three layers of activity:
    1. Aggressive takes  — hit obvious mispricings (ask < FV - TAKE_EDGE or bid > FV + TAKE_EDGE).
    2. Passive quotes    — post bid/ask at FV ± QUOTE_HALF, shifted by inventory.
    3. EMA fair value    — slow EMA tracks any structural drift away from 10,000.
    """

    def __init__(
        self,
        symbol: str = SYMBOL,
        position_limit: int = POSITION_LIMIT,
        fair_value_init: float = FAIR_VALUE_INIT,
        ema_alpha: float = EMA_ALPHA,
        quote_half: int = QUOTE_HALF,
        skew_divisor: int = SKEW_DIVISOR,
        take_edge: int = TAKE_EDGE,
    ):
        super().__init__(symbol, position_limit)
        self.fair_value_init = fair_value_init
        self.ema_alpha = ema_alpha
        self.quote_half = quote_half
        self.skew_divisor = skew_divisor
        self.take_edge = take_edge
        self.fv: float | None = None

    # --- state persistence ---

    def load_state(self, data: dict) -> None:
        self.fv = data.get(self.symbol + "_fv", self.fair_value_init)

    def dump_state(self, data: dict) -> None:
        data[self.symbol + "_fv"] = self.fv

    # --- core logic ---

    def get_orders(self, state: TradingState) -> List[Order]:
        orders: List[Order] = []

        od = state.order_depths.get(self.symbol)
        if od is None:
            return orders

        mid = self.mid_price(od)
        if mid is None:
            # One-sided book — still update EMA with what we have, skip quoting
            return orders

        # Update fair-value EMA
        if self.fv is None:
            self.fv = mid
        else:
            self.fv = self.ema_alpha * mid + (1 - self.ema_alpha) * self.fv

        fv = self.fv
        pos = self.current_position(state)
        best_ask = self.best_ask(od)
        best_bid = self.best_bid(od)

        # ── 1. Aggressive takes ───────────────────────────────────────────────
        if best_ask is not None and best_ask < fv - self.take_edge:
            qty = min(-od.sell_orders[best_ask], self.position_limit - pos)
            if qty > 0:
                orders.append(Order(self.symbol, best_ask, qty))
                pos += qty

        if best_bid is not None and best_bid > fv + self.take_edge:
            qty = min(od.buy_orders[best_bid], self.position_limit + pos)
            if qty > 0:
                orders.append(Order(self.symbol, best_bid, -qty))
                pos -= qty

        # ── 2. Passive market-making with inventory skew ──────────────────────
        skew = round(pos / self.skew_divisor)
        my_bid = round(fv) - self.quote_half - skew
        my_ask = round(fv) + self.quote_half - skew

        buy_capacity  = self.position_limit - pos
        sell_capacity = self.position_limit + pos

        if buy_capacity > 0:
            orders.append(Order(self.symbol, my_bid, buy_capacity))
        if sell_capacity > 0:
            orders.append(Order(self.symbol, my_ask, -sell_capacity))

        return orders

# --- commodity.py ---
from datamodel import Order, TradingState
from typing import List


class CommodityTrader(ProductTrader):
    """
    Conversion arbitrage for commodity products with a conversion mechanism.
    Exploits price gaps between the exchange price and conversion value.
    """

    def __init__(self, symbol: str, position_limit: int, conversion_cost: float, threshold: float = 1.0):
        """
        Args:
            symbol: Tradeable symbol on the exchange.
            position_limit: Max position.
            conversion_cost: Total cost (fees + transport) per unit converted.
            threshold: Min profit above conversion_cost to trigger conversion.
        """
        super().__init__(symbol, position_limit)
        self.conversion_cost = conversion_cost
        self.threshold = threshold

    def get_orders(self, state: TradingState) -> List[Order]:
        orders: List[Order] = []

        obs = state.observations.conversionObservations.get(self.symbol)
        order_depth = state.order_depths.get(self.symbol)
        if obs is None or order_depth is None:
            return orders

        # obs attributes depend on the round — adapt accordingly
        # e.g. obs.bidPrice, obs.askPrice, obs.transportFees, obs.importTariff
        conversion_ask = getattr(obs, "askPrice", None)
        conversion_bid = getattr(obs, "bidPrice", None)

        exch_bid = self.best_bid(order_depth)
        exch_ask = self.best_ask(order_depth)

        pos = self.current_position(state)

        if conversion_ask is not None and exch_bid is not None:
            profit = exch_bid - conversion_ask - self.conversion_cost
            if profit > self.threshold and pos > -self.position_limit:
                orders.append(Order(self.symbol, exch_bid, -1))

        if conversion_bid is not None and exch_ask is not None:
            profit = conversion_bid - exch_ask - self.conversion_cost
            if profit > self.threshold and pos < self.position_limit:
                orders.append(Order(self.symbol, exch_ask, 1))

        return orders

# --- dynamic_product.py ---
from datamodel import Order, TradingState
from typing import List
from collections import deque


class DynamicProductTrader(ProductTrader):
    """
    Market-making strategy for random-walk / non-stationary products.
    Estimates fair value from a rolling mid-price EMA.
    """

    def __init__(self, symbol: str, position_limit: int, ema_alpha: float = 0.2, half_spread: int = 2):
        super().__init__(symbol, position_limit)
        self.ema_alpha = ema_alpha
        self.half_spread = half_spread
        self.ema: float | None = None

    def get_orders(self, state: TradingState) -> List[Order]:
        orders: List[Order] = []
        order_depth = state.order_depths.get(self.symbol)
        if order_depth is None:
            return orders

        mid = self.mid_price(order_depth)
        if mid is None:
            return orders

        if self.ema is None:
            self.ema = mid
        else:
            self.ema = self.ema_alpha * mid + (1 - self.ema_alpha) * self.ema

        pos = self.current_position(state)
        bid_price = round(self.ema - self.half_spread)
        ask_price = round(self.ema + self.half_spread)

        buy_capacity = self.position_limit - pos
        sell_capacity = self.position_limit + pos

        if buy_capacity > 0:
            orders.append(Order(self.symbol, bid_price, buy_capacity))
        if sell_capacity > 0:
            orders.append(Order(self.symbol, ask_price, -sell_capacity))

        return orders

# --- etf_arb.py ---
from datamodel import Order, TradingState
from typing import List


class ETFArbTrader:
    """
    Spread / ETF arbitrage between a basket and its constituents.
    Trades the ETF vs. a weighted combination of component symbols.
    """

    def __init__(self, etf_symbol: str, components: dict[str, float], position_limit: int, threshold: float = 2.0):
        """
        Args:
            etf_symbol: Symbol for the ETF / basket product.
            components: {symbol: weight} mapping for constituents.
            position_limit: Max position on each leg.
            threshold: Min spread (in price units) to trigger a trade.
        """
        self.etf_symbol = etf_symbol
        self.components = components
        self.position_limit = position_limit
        self.threshold = threshold

    def get_orders(self, state: TradingState) -> List[Order]:
        orders: List[Order] = []

        etf_depth = state.order_depths.get(self.etf_symbol)
        if etf_depth is None:
            return orders

        # Compute synthetic NAV from component mid prices
        nav = 0.0
        for symbol, weight in self.components.items():
            depth = state.order_depths.get(symbol)
            if depth is None:
                return orders
            bid = max(depth.buy_orders) if depth.buy_orders else None
            ask = min(depth.sell_orders) if depth.sell_orders else None
            if bid is None or ask is None:
                return orders
            nav += weight * (bid + ask) / 2

        etf_bid = max(etf_depth.buy_orders) if etf_depth.buy_orders else None
        etf_ask = min(etf_depth.sell_orders) if etf_depth.sell_orders else None

        if etf_bid is not None and etf_bid - nav > self.threshold:
            # ETF overpriced — sell ETF, buy components
            orders.append(Order(self.etf_symbol, etf_bid, -1))

        if etf_ask is not None and nav - etf_ask > self.threshold:
            # ETF underpriced — buy ETF, sell components
            orders.append(Order(self.etf_symbol, etf_ask, 1))

        return orders

# --- options.py ---
import math
from datamodel import Order, TradingState
from typing import List


def black_scholes_call(S: float, K: float, T: float, r: float, sigma: float) -> float:
    if T <= 0:
        return max(S - K, 0.0)
    d1 = (math.log(S / K) + (r + 0.5 * sigma ** 2) * T) / (sigma * math.sqrt(T))
    d2 = d1 - sigma * math.sqrt(T)
    return S * _norm_cdf(d1) - K * math.exp(-r * T) * _norm_cdf(d2)


def implied_vol(market_price: float, S: float, K: float, T: float, r: float,
                tol: float = 1e-6, max_iter: int = 100) -> float:
    """Newton-Raphson IV solver."""
    sigma = 0.5
    for _ in range(max_iter):
        price = black_scholes_call(S, K, T, r, sigma)
        vega = S * math.sqrt(T) * _norm_pdf((math.log(S / K) + (r + 0.5 * sigma ** 2) * T) / (sigma * math.sqrt(T)))
        if vega < 1e-10:
            break
        sigma -= (price - market_price) / vega
        sigma = max(sigma, 1e-6)
        if abs(price - market_price) < tol:
            break
    return sigma


def _norm_cdf(x: float) -> float:
    return (1.0 + math.erf(x / math.sqrt(2.0))) / 2.0


def _norm_pdf(x: float) -> float:
    return math.exp(-0.5 * x ** 2) / math.sqrt(2 * math.pi)


class OptionsTrader(ProductTrader):
    """
    IV scalping strategy for options products.
    Buys options when IV is below fair_iv, sells when above.
    """

    def __init__(self, symbol: str, position_limit: int, underlying_symbol: str,
                 K: float, T: float, r: float, fair_iv: float, iv_edge: float = 0.02):
        super().__init__(symbol, position_limit)
        self.underlying_symbol = underlying_symbol
        self.K = K
        self.T = T
        self.r = r
        self.fair_iv = fair_iv
        self.iv_edge = iv_edge

    def get_orders(self, state: TradingState) -> List[Order]:
        orders: List[Order] = []

        opt_depth = state.order_depths.get(self.symbol)
        und_depth = state.order_depths.get(self.underlying_symbol)
        if opt_depth is None or und_depth is None:
            return orders

        S_mid = self.mid_price(und_depth)
        if S_mid is None:
            return orders

        opt_ask = min(opt_depth.sell_orders) if opt_depth.sell_orders else None
        opt_bid = max(opt_depth.buy_orders) if opt_depth.buy_orders else None

        pos = self.current_position(state)

        if opt_ask is not None:
            iv = implied_vol(opt_ask, S_mid, self.K, self.T, self.r)
            if iv < self.fair_iv - self.iv_edge and pos < self.position_limit:
                orders.append(Order(self.symbol, opt_ask, 1))

        if opt_bid is not None:
            iv = implied_vol(opt_bid, S_mid, self.K, self.T, self.r)
            if iv > self.fair_iv + self.iv_edge and pos > -self.position_limit:
                orders.append(Order(self.symbol, opt_bid, -1))

        return orders

# --- pepper_mr.py ---
from datamodel import Order, TradingState
from typing import List

SYMBOL = "INTARIAN_PEPPER_ROOT"
POSITION_LIMIT = 50


class PepperMeanReversionTrader(ProductTrader):
    """
    Mean-reversion strategy for INTARIAN_PEPPER_ROOT.

    Logic:
    - Maintains a rolling EMA of the wall mid-price.
    - Goes max-long  when mid < EMA - threshold  (price below fair value).
    - Goes max-short when mid > EMA + threshold  (price above fair value).
    - Flattens toward zero when mid is within the band (no edge).

    State (ema) is persisted across ticks via traderData JSON so that
    the EMA survives re-instantiation on every tick.
    """

    def __init__(
        self,
        symbol: str = SYMBOL,
        position_limit: int = POSITION_LIMIT,
        ema_alpha: float = 0.15,
        threshold: float = 3.0,
    ):
        super().__init__(symbol, position_limit)
        self.ema_alpha = ema_alpha
        self.threshold = threshold
        self.ema: float | None = None

    # ------------------------------------------------------------------
    # State persistence
    # ------------------------------------------------------------------

    def load_state(self, data: dict) -> None:
        self.ema = data.get(self.symbol + "_ema")

    def dump_state(self, data: dict) -> None:
        data[self.symbol + "_ema"] = self.ema

    # ------------------------------------------------------------------
    # Core logic
    # ------------------------------------------------------------------

    def get_orders(self, state: TradingState) -> List[Order]:
        orders: List[Order] = []

        order_depth = state.order_depths.get(self.symbol)
        if order_depth is None:
            return orders

        mid = self.mid_price(order_depth)
        if mid is None:
            return orders

        # Update EMA — warm-start on first tick
        if self.ema is None:
            self.ema = mid
        else:
            self.ema = self.ema_alpha * mid + (1 - self.ema_alpha) * self.ema

        pos = self.current_position(state)
        best_ask = self.best_ask(order_depth)
        best_bid = self.best_bid(order_depth)

        deviation = mid - self.ema

        if deviation < -self.threshold:
            # Price is cheap relative to EMA — go long
            if best_ask is not None:
                buy_qty = self.position_limit - pos   # fill up to limit
                if buy_qty > 0:
                    orders.append(Order(self.symbol, best_ask, buy_qty))

        elif deviation > self.threshold:
            # Price is rich relative to EMA — go short
            if best_bid is not None:
                sell_qty = self.position_limit + pos  # sell down to -limit
                if sell_qty > 0:
                    orders.append(Order(self.symbol, best_bid, -sell_qty))

        else:
            # Inside the band — exit any open position
            if pos > 0 and best_bid is not None:
                orders.append(Order(self.symbol, best_bid, -pos))
            elif pos < 0 and best_ask is not None:
                orders.append(Order(self.symbol, best_ask, -pos))

        return orders

# --- pepper_trend.py ---
from datamodel import Order, TradingState
from typing import List
import math

SYMBOL = "INTARIAN_PEPPER_ROOT"
POSITION_LIMIT = 50

# Pepper drifted +3,000 over 3 days — it is non-stationary.  Mean-reversion
# loses money here.  Instead we ride the trend by quoting asymmetrically:
#   bid close to EMA  →  gets filled on dips, accumulating long exposure
#   ask far above EMA →  only sells when price is genuinely extended

EMA_ALPHA = 0.15        # moderately fast; tracks the trend without chasing ticks

# Quote offsets from EMA.  Both must exceed the half-spread (~6.5) so that
# passive fills are net-profitable.  Wider ask biases the book long.
BID_OFFSET = 5          # post bid at EMA - 5  (just inside the market, earns spread)
ASK_OFFSET = 10         # post ask at EMA + 10 (only sell if price very extended)

# Opportunistic take: cross the ask aggressively only when the price is well
# below the EMA — must exceed the half-spread to ensure positive expectancy.
TAKE_DIP_THRESHOLD = 9  # buy at market if best_ask < EMA - 9

# Order-book imbalance filter.  If the top-of-book is overwhelmingly one-sided,
# suppress the quote on the crowded side to avoid being run over.
OBI_BUY_PRESSURE  = 0.75   # obi > this → huge buy wall → pause asks
OBI_SELL_PRESSURE = 0.25   # obi < this → huge sell wall → pause bids

# Inventory skew: as we approach the position limit, widen the quote on the
# side that would increase exposure further, to slow down accumulation.
SKEW_DIVISOR = 8


class PepperTrendTrader(ProductTrader):
    """
    Trend-following market-maker for INTARIAN_PEPPER_ROOT.

    Key design choices vs the previous mean-reversion strategy:
    - NO mean-reversion entries.  Pepper is trending; fading moves loses money.
    - Asymmetric quoting: bid offset < ask offset → net long bias.
    - Quote offsets are both > half-spread (~6.5) so passive fills are profitable.
    - OBI filter pauses one side when the book is heavily one-sided.
    - Opportunistic aggressive buy only when dip exceeds the half-spread.
    - Inventory skew slows accumulation near the position limit.
    """

    def __init__(
        self,
        symbol: str = SYMBOL,
        position_limit: int = POSITION_LIMIT,
        ema_alpha: float = EMA_ALPHA,
        bid_offset: int = BID_OFFSET,
        ask_offset: int = ASK_OFFSET,
        take_dip_threshold: int = TAKE_DIP_THRESHOLD,
        obi_buy_pressure: float = OBI_BUY_PRESSURE,
        obi_sell_pressure: float = OBI_SELL_PRESSURE,
        skew_divisor: int = SKEW_DIVISOR,
    ):
        super().__init__(symbol, position_limit)
        self.ema_alpha = ema_alpha
        self.bid_offset = bid_offset
        self.ask_offset = ask_offset
        self.take_dip_threshold = take_dip_threshold
        self.obi_buy_pressure = obi_buy_pressure
        self.obi_sell_pressure = obi_sell_pressure
        self.skew_divisor = skew_divisor
        self.ema: float | None = None

    # --- state persistence ---

    def load_state(self, data: dict) -> None:
        self.ema = data.get(self.symbol + "_ema")

    def dump_state(self, data: dict) -> None:
        data[self.symbol + "_ema"] = self.ema

    # --- core logic ---

    def get_orders(self, state: TradingState) -> List[Order]:
        orders: List[Order] = []

        od = state.order_depths.get(self.symbol)
        if od is None:
            return orders

        best_bid = self.best_bid(od)
        best_ask = self.best_ask(od)
        if best_bid is None or best_ask is None:
            return orders

        mid = (best_bid + best_ask) / 2

        # Update EMA
        if self.ema is None:
            self.ema = mid
        else:
            self.ema = self.ema_alpha * mid + (1 - self.ema_alpha) * self.ema

        ema = self.ema
        pos = self.current_position(state)

        # ── OBI calculation ───────────────────────────────────────────────────
        bid_vol = od.buy_orders.get(best_bid, 0)
        ask_vol = abs(od.sell_orders.get(best_ask, 0))
        total_vol = bid_vol + ask_vol
        obi = bid_vol / total_vol if total_vol > 0 else 0.5

        allow_buy  = obi >= self.obi_sell_pressure   # suppress bids if sell wall
        allow_sell = obi <= self.obi_buy_pressure    # suppress asks if buy wall

        # ── 1. Opportunistic take on deep dip ─────────────────────────────────
        # Only cross the spread when the dip is large enough to guarantee profit
        # after paying the spread (threshold > half-spread of ~6.5).
        if allow_buy and best_ask < ema - self.take_dip_threshold:
            qty = min(ask_vol, self.position_limit - pos)
            if qty > 0:
                orders.append(Order(self.symbol, best_ask, qty))
                pos += qty

        # ── 2. Passive asymmetric quotes with inventory skew ──────────────────
        skew = round(pos / self.skew_divisor)

        # Shift both quotes down when long (skew > 0) to slow long accumulation
        # and encourage selling; shift up when short to encourage buying.
        my_bid = math.floor(ema) - self.bid_offset - skew
        my_ask = math.ceil(ema)  + self.ask_offset - skew

        buy_capacity  = self.position_limit - pos
        sell_capacity = self.position_limit + pos

        if allow_buy and buy_capacity > 0:
            orders.append(Order(self.symbol, my_bid, buy_capacity))

        if allow_sell and sell_capacity > 0:
            orders.append(Order(self.symbol, my_ask, -sell_capacity))

        return orders

# --- static_product.py ---
from datamodel import Order, TradingState
from typing import List


class StaticProductTrader(ProductTrader):
    """
    Market-making strategy for stationary / mean-reverting products.
    Quotes around a fair value with a configurable spread.
    """

    def __init__(self, symbol: str, position_limit: int, fair_value: float, half_spread: int = 1):
        super().__init__(symbol, position_limit)
        self.fair_value = fair_value
        self.half_spread = half_spread

    def get_orders(self, state: TradingState) -> List[Order]:
        orders: List[Order] = []
        pos = self.current_position(state)

        bid_price = round(self.fair_value - self.half_spread)
        ask_price = round(self.fair_value + self.half_spread)

        buy_capacity = self.position_limit - pos
        sell_capacity = self.position_limit + pos

        if buy_capacity > 0:
            orders.append(Order(self.symbol, bid_price, buy_capacity))
        if sell_capacity > 0:
            orders.append(Order(self.symbol, ask_price, -sell_capacity))

        return orders

# --- trader_v1.py ---
from datamodel import OrderDepth, UserId, TradingState, Order
from typing import List, Dict
import json
import math

class Trader:
    def __init__(self):
        # Set your position limits here. (Update these if Round 1 rules specify different limits)
        self.POSITION_LIMITS = {
            "ASH_COATED_OSMIUM": 20,
            "INTARIAN_PEPPER_ROOT": 20
        }
        
        # Configuration for ASH_COATED_OSMIUM (Stationary)
        self.ASH_FAIR_VALUE = 10000
        
        # Configuration for INTARIAN_PEPPER_ROOT (Trending)
        self.PEPPER_EMA_ALPHA = 0.2  # Smoothing factor (higher = reacts to price changes faster)

    def run(self, state: TradingState):
        """
        Only method required. It takes all inputs and returns a tuple of (orders, conversions, trader_data).
        """
        # Dictionary to hold the orders for each product
        result = {}
        
        # We start by parsing the persistent state from the previous timestamp (used for the EMA)
        trader_data = {}
        if state.traderData:
            try:
                trader_data = json.loads(state.traderData)
            except Exception as e:
                pass # If it's the first timestamp or corrupted, start fresh
                
        # ---------------------------------------------------------
        # 1. Process ASH_COATED_OSMIUM (The "Anchor" Strategy)
        # ---------------------------------------------------------
        ash_product = "ASH_COATED_OSMIUM"
        if ash_product in state.order_depths:
            order_depth: OrderDepth = state.order_depths[ash_product]
            orders: List[Order] = []
            
            # Get current position and calculate limits
            current_position = state.position.get(ash_product, 0)
            limit = self.POSITION_LIMITS[ash_product]
            
            # --- MARKET TAKING (Clear "Free Money") ---
            # Buy if someone is selling below fair value
            if len(order_depth.sell_orders) != 0:
                best_ask, best_ask_amount = list(order_depth.sell_orders.items())[0]
                if best_ask < self.ASH_FAIR_VALUE:
                    buy_amount = min(-best_ask_amount, limit - current_position)
                    if buy_amount > 0:
                        orders.append(Order(ash_product, best_ask, buy_amount))
                        current_position += buy_amount

            # Sell if someone is buying above fair value
            if len(order_depth.buy_orders) != 0:
                best_bid, best_bid_amount = list(order_depth.buy_orders.items())[0]
                if best_bid > self.ASH_FAIR_VALUE:
                    sell_amount = max(-best_bid_amount, -limit - current_position) # sell amounts are negative
                    if sell_amount < 0:
                        orders.append(Order(ash_product, best_bid, sell_amount))
                        current_position += sell_amount

            # --- MARKET MAKING (Capture the spread) ---
            # How much room do we have left to trade?
            max_buy = limit - current_position
            max_sell = -limit - current_position

            # Shift quotes based on inventory to prevent hitting the limit
            position_skew = int(current_position / 4)
            
            my_bid = self.ASH_FAIR_VALUE - 4 - position_skew
            my_ask = self.ASH_FAIR_VALUE + 4 - position_skew

            # Place the passive orders if we have room
            if max_buy > 0:
                orders.append(Order(ash_product, my_bid, max_buy))
            if max_sell < 0:
                orders.append(Order(ash_product, my_ask, max_sell))

            result[ash_product] = orders


        # ---------------------------------------------------------
        # 2. Process INTARIAN_PEPPER_ROOT (The "Escalator" + OBI Protection)
        # ---------------------------------------------------------
        pepper_product = "INTARIAN_PEPPER_ROOT"
        if pepper_product in state.order_depths:
            order_depth: OrderDepth = state.order_depths[pepper_product]
            orders: List[Order] = []
            
            current_position = state.position.get(pepper_product, 0)
            limit = self.POSITION_LIMITS[pepper_product]
            
            if len(order_depth.sell_orders) > 0 and len(order_depth.buy_orders) > 0:
                best_ask, best_ask_amount = list(order_depth.sell_orders.items())[0]
                best_bid, best_bid_amount = list(order_depth.buy_orders.items())[0]
                mid_price = (best_ask + best_bid) / 2.0
                
                # --- ORDER BOOK IMBALANCE (OBI) CALCULATION ---
                # Note: ask amounts are negative in the datamodel, so we use abs()
                total_volume = best_bid_amount + abs(best_ask_amount)
                obi = best_bid_amount / total_volume if total_volume > 0 else 0.5
            else:
                mid_price = None

            if mid_price is not None:
                # Update Exponential Moving Average (EMA)
                prev_ema = trader_data.get("pepper_ema", mid_price)
                current_ema = (self.PEPPER_EMA_ALPHA * mid_price) + ((1 - self.PEPPER_EMA_ALPHA) * prev_ema)
                trader_data["pepper_ema"] = current_ema
                
                my_bid = math.floor(current_ema - 3)
                my_ask = math.ceil(current_ema + 6) 
                
                max_buy = limit - current_position
                max_sell = -limit - current_position
                
                # --- OBI PROTECTION LOGIC ---
                if obi > 0.8:
                    # Massive buying pressure: Price is about to spike!
                    # Cancel our market-making asks so we don't get run over.
                    max_sell = 0 
                elif obi < 0.2:
                    # Massive selling pressure: Price is about to dump!
                    # Cancel our market-making bids so we don't catch a falling knife.
                    max_buy = 0
                
                # Opportunistic Market Taking: Aggressive buy if price dips significantly below the EMA
                # (We still allow this even if OBI is low, because a massive dip below EMA is highly profitable)
                if best_ask < current_ema - 2:
                    buy_amount = min(abs(best_ask_amount), max_buy)
                    if buy_amount > 0:
                        orders.append(Order(pepper_product, best_ask, buy_amount))
                        max_buy -= buy_amount
                        current_position += buy_amount
                        max_sell = -limit - current_position # Re-adjust sell limit after taking
                
                # Place Market Making Orders around the moving average (filtered by OBI)
                if max_buy > 0:
                    orders.append(Order(pepper_product, my_bid, max_buy))
                if max_sell < 0: # Note: max_sell is negative, so this checks if we still want to sell
                    orders.append(Order(pepper_product, my_ask, max_sell))
                    
            result[pepper_product] = orders

        # ---------------------------------------------------------
        # 3. Finalize and Return
        # ---------------------------------------------------------
        
        # Serialize the trader data state so it can be passed into the next timestamp
        next_trader_data = json.dumps(trader_data)
        conversions = 0 # No conversions in Round 1 usually
        
        return result, conversions, next_trader_data
class Trader:
    def run(self, state: TradingState):
        # Safe default template: place no orders.
        # Returning unknown product keys can crash some backtester configs.
        return {}, 0, ""
